import data from "@/data/data.json";
import { routing } from "@/i18n/routing";

const domain = process.env.NEXT_PUBLIC_DOMAIN || "imleo.it";

/** English lives at the root; every other locale gets a path prefix. */
export function localeUrl(locale: string) {
  const base = `https://${domain}`;
  return locale === "en" ? base : `${base}/${locale}`;
}

/**
 * Google wants a language-region pair whenever the audience is regional. This
 * site is aimed at Alto Adige / Südtirol first, so `it` and `de` both carry
 * regional twins and the bare code stays as the catch-all.
 */
export const HREFLANG: Record<string, string[]> = {
  en: ["en", "en-GB", "en-US"],
  it: ["it", "it-IT"],
  de: ["de", "de-DE", "de-AT", "de-CH"],
  es: ["es", "es-ES"],
};

/** Builds the `alternates.languages` map for any path under a locale root. */
export function languageAlternates(suffix = "") {
  const languages: Record<string, string> = {};
  for (const locale of routing.locales) {
    for (const tag of HREFLANG[locale] ?? [locale]) {
      languages[tag] = `${localeUrl(locale)}${suffix}`;
    }
  }
  languages["x-default"] = `${localeUrl(routing.defaultLocale)}${suffix}`;
  return languages;
}

export const SEO_CONFIG = {
  baseUrl: `https://${domain}`,
  domain,
  title: "Leonardo Parisi — Front-End Developer in Bolzano, Italy",
  description:
    "Leonardo Parisi is a front-end developer based in Bolzano (Bozen), Italy, building fast, accessible websites and interfaces with React, Next.js and TypeScript.",
  author: "Leonardo Parisi",
  email: data.contact.email,
  // E.164, no spaces — what schema.org's `telephone` and Google's own
  // validator expect; the spaced form stays in data.json for the UI.
  phone: data.contact.phone.replace(/\s/g, ""),
  twitter: "@_leoparisi",
  // Piazza Walther — close enough to place the practice in the centre of
  // Bolzano for "near me" queries without publishing a home address to a map.
  geo: { latitude: 46.4983, longitude: 11.3548 },
  address: {
    streetAddress: "Via Palermo 46",
    postalCode: "39100",
    addressLocality: "Bolzano",
    addressRegion: "Trentino-Alto Adige/Südtirol",
    addressCountry: "IT",
  },
  vatID: `IT${data.contact.vat}`,
  socialLinks: data.socials.map((s) => s.url),
  languages: ["it", "en", "de"],
  skills: [
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "Framer Motion",
    "Web Performance",
    "Web Accessibility",
    "Responsive Web Design",
    "Frontend Architecture",
    "UI/UX Implementation",
    "SEO",
  ],
  /**
   * Not emitted as a `<meta name="keywords">` for ranking — Google ignores
   * that — but reused as the `keywords` field of the schema graph, where it
   * does help entity matching.
   */
  keywords: [
    "front-end developer Bolzano",
    "frontend developer Bolzano",
    "sviluppatore front-end Bolzano",
    "sviluppatore web Bolzano",
    "Frontend-Entwickler Bozen",
    "Webentwickler Bozen",
    "Leonardo Parisi",
    "italian front-end developer",
    "React developer Bolzano",
    "Next.js developer Italy",
    "web designer Alto Adige",
    "creazione siti web Bolzano",
  ],
};

const ID = {
  person: `${SEO_CONFIG.baseUrl}/#person`,
  website: `${SEO_CONFIG.baseUrl}/#website`,
  business: `${SEO_CONFIG.baseUrl}/#business`,
};

const postalAddress = {
  "@type": "PostalAddress",
  ...SEO_CONFIG.address,
};

const areaServed = [
  { "@type": "City", name: "Bolzano" },
  { "@type": "City", name: "Bozen" },
  { "@type": "AdministrativeArea", name: "Alto Adige / Südtirol" },
  { "@type": "AdministrativeArea", name: "Trentino-Alto Adige" },
  { "@type": "Country", name: "Italy" },
];

/**
 * The card generated by app/[locale]/opengraph-image.tsx. The default locale
 * serves it unprefixed, which keeps one stable URL for the schema graph and
 * the sitemap even as the hashed `og:image` URL changes between builds.
 */
const ogImage = `${SEO_CONFIG.baseUrl}/opengraph-image`;

function personSchema(locale: string, jobTitle: string, description: string) {
  return {
    "@type": "Person",
    "@id": ID.person,
    name: SEO_CONFIG.author,
    givenName: "Leonardo",
    familyName: "Parisi",
    alternateName: "imleo",
    description,
    email: `mailto:${SEO_CONFIG.email}`,
    telephone: SEO_CONFIG.phone,
    url: SEO_CONFIG.baseUrl,
    mainEntityOfPage: localeUrl(locale),
    image: ogImage,
    jobTitle,
    hasOccupation: {
      "@type": "Occupation",
      name: jobTitle,
      occupationLocation: { "@type": "City", name: "Bolzano" },
      skills: SEO_CONFIG.skills.join(", "),
    },
    worksFor: { "@id": ID.business },
    nationality: { "@type": "Country", name: "Italy" },
    knowsLanguage: SEO_CONFIG.languages,
    knowsAbout: SEO_CONFIG.skills,
    homeLocation: { "@type": "Place", address: postalAddress },
    address: postalAddress,
    sameAs: SEO_CONFIG.socialLinks,
    vatID: SEO_CONFIG.vatID,
  };
}

function businessSchema(name: string, description: string) {
  return {
    "@type": "ProfessionalService",
    "@id": ID.business,
    name,
    description,
    url: SEO_CONFIG.baseUrl,
    image: ogImage,
    logo: `${SEO_CONFIG.baseUrl}/icon.png`,
    email: `mailto:${SEO_CONFIG.email}`,
    telephone: SEO_CONFIG.phone,
    founder: { "@id": ID.person },
    employee: { "@id": ID.person },
    address: postalAddress,
    geo: {
      "@type": "GeoCoordinates",
      latitude: SEO_CONFIG.geo.latitude,
      longitude: SEO_CONFIG.geo.longitude,
    },
    areaServed,
    serviceType: [
      "Front-end web development",
      "Website design and development",
      "React and Next.js development",
      "Web performance optimisation",
      "Web accessibility",
    ],
    knowsLanguage: SEO_CONFIG.languages,
    vatID: SEO_CONFIG.vatID,
    priceRange: "€€",
    currenciesAccepted: "EUR",
    sameAs: SEO_CONFIG.socialLinks,
    hasOfferCatalog: {
      "@type": "OfferCatalog",
      name: "Front-end development services",
      itemListElement: [
        "Website design and build",
        "React / Next.js applications",
        "Landing pages and portfolios",
        "Performance and SEO audits",
      ].map((service) => ({
        "@type": "Offer",
        itemOffered: { "@type": "Service", name: service },
      })),
    },
  };
}

function websiteSchema(locale: string, title: string, description: string) {
  return {
    "@type": "WebSite",
    "@id": ID.website,
    url: SEO_CONFIG.baseUrl,
    name: title,
    alternateName: ["Leonardo Parisi Portfolio", SEO_CONFIG.domain],
    description,
    inLanguage: [...routing.locales],
    publisher: { "@id": ID.person },
    copyrightHolder: { "@id": ID.person },
    keywords: SEO_CONFIG.keywords.join(", "),
    mainEntity: { "@id": ID.person },
    potentialAction: { "@type": "ReadAction", target: [localeUrl(locale)] },
  };
}

/** The visible project list, mirrored so the work section is machine-readable. */
function workSchema(locale: string) {
  return {
    "@type": "ItemList",
    "@id": `${localeUrl(locale)}#work`,
    name: "Selected work",
    numberOfItems: data.work.length,
    itemListElement: data.work.map((project, index) => ({
      "@type": "ListItem",
      position: index + 1,
      item: {
        "@type": "CreativeWork",
        name: project.company,
        url: project.url,
        author: { "@id": ID.person },
        keywords: project.stack.join(", "),
      },
    })),
  };
}

/**
 * One `@graph` per page instead of a handful of loose blocks: the nodes
 * reference each other by `@id`, which is what lets a crawler resolve the
 * person, the business and the page into a single entity.
 */
export function generateGraph({
  locale,
  title,
  description,
  jobTitle,
  businessName,
}: {
  locale: string;
  title: string;
  description: string;
  jobTitle: string;
  businessName: string;
}) {
  const url = localeUrl(locale);

  return {
    "@context": "https://schema.org",
    "@graph": [
      websiteSchema(locale, title, description),
      {
        "@type": "ProfilePage",
        "@id": `${url}#page`,
        url,
        name: title,
        description,
        inLanguage: locale,
        isPartOf: { "@id": ID.website },
        about: { "@id": ID.person },
        mainEntity: { "@id": ID.person },
        primaryImageOfPage: ogImage,
      },
      personSchema(locale, jobTitle, description),
      businessSchema(businessName, description),
      workSchema(locale),
    ],
  };
}

/** Legal pages: a plain WebPage plus the breadcrumb back to the portfolio. */
export function generateLegalGraph({
  locale,
  slug,
  title,
  description,
  homeLabel,
}: {
  locale: string;
  slug: string;
  title: string;
  description: string;
  homeLabel: string;
}) {
  const url = `${localeUrl(locale)}/${slug}`;

  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `${url}#page`,
        url,
        name: title,
        description,
        inLanguage: locale,
        isPartOf: { "@id": ID.website },
        publisher: { "@id": ID.person },
      },
      {
        "@type": "BreadcrumbList",
        "@id": `${url}#breadcrumb`,
        itemListElement: [
          {
            "@type": "ListItem",
            position: 1,
            name: homeLabel,
            item: localeUrl(locale),
          },
          { "@type": "ListItem", position: 2, name: title, item: url },
        ],
      },
    ],
  };
}
